### ISSUE TITLE
Error when creating a DenoiCompNet

### ISSUE THREAD

**Issue by guilhermebene** [openspyrit/spyrit#39]
Following the updates from PR #37, where `misc/statistics` was added, I am now getting an error when creating a DenoiCompNet using spas. It seems Cov2Var cannot be found.

```
Traceback (most recent call last):

  File "C:\Users\beneti\spas\scripts\acquisition-recon-sequential.py", line 63, in <module>
    model, device = setup_reconstruction(cov_path, mean_path, H, model_root, network_params)

  File "c:\users\beneti\spas\spas\reconstruction_nn.py", line 146, in setup_reconstruction
    model = DenoiCompNet(

  File "c:\users\beneti\spyrit\spyrit\learning\model_Had_DCAN.py", line 598, in __init__
    super().__init__(n, M, Mean, Cov, variant, N0, sig, H, Ord)

  File "c:\users\beneti\spyrit\spyrit\learning\model_Had_DCAN.py", line 531, in __init__
    super().__init__(n, M, Mean, Cov, variant, H, Ord)

  File "c:\users\beneti\spyrit\spyrit\learning\model_Had_DCAN.py", line 336, in __init__
    Ord = Cov2Var(Cov)

NameError: name 'Cov2Var' is not defined
```

**Comment by nducros** [comment]
Right,  `Cov2Var` is now in `misc/statistics`. Can you update master with the import ?

**Comment by guilhermebene** [comment]
I am not sure... I might test this in another case rather than in spas to see if I can reproduce the error.
